#sudo docker-compose -f docker-compose.production.yml up --build --force-recreate -d
version: '3'

services:
  app:
    image: docker-next
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
    - 3000:3000