#sudo docker-compose up --build --force-recreate -d
version: "3"

services:
  postgres:
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: 
      - /.env.test

  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - next-dev-vol:/app