#sudo docker-compose up --build --force-recreate -d
version: "3"

services:
  app:
    image: docker-nextjs-dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    
  node:
    image: node:20.2.0
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test