#sudo docker-compose up --build --force-recreate -d
version: "3"

services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - next-dev-vol:.

  node:
    image: node:20.2.0
    volumes:
      - next-dev-vol:.

volumes:
  next-dev-vol: